# Generated by Django 6.0.5 on 2026-06-09 16:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
        migrations.CreateModel(
            name="ObjectVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("model_type", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=200)),
                ("route", models.CharField(max_length=200)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                "unique_together": {("object_id", "model_type")},
            },
        ),
    ]
