"""
Basic tests for the integrate API endpoints.

Uses SimpleTestCase with mocked viewset methods so no database connection
is required — tests run in any environment without Docker.
"""

from django.http import Http404
from django.test import SimpleTestCase
from unittest.mock import patch, MagicMock
from integrate.models import Disciplina, Tema, Jogo, Livro, Exercicio, Aula
from integrate.views import (
    DisciplinaViewSet,
    TemaViewSet,
    JogoViewSet,
    LivroViewSet,
    ExercicioViewSet,
    AulaViewSet,
)

# Fake model instances (unsaved — UUIDs auto-generated by field default


def _disciplina(**kw):
    """Build an unsaved Disciplina instance."""
    return Disciplina(
        nome=kw.get("nome", "Matemática"),
        slug=kw.get("slug", "matematica"),
        desc=kw.get("desc", "Descrição"),
    )


def _tema(**kw):
    """Build an unsaved Tema instance with a linked Disciplina."""
    d = _disciplina()
    return Tema(
        titulo=kw.get("titulo", "Adição"),
        slug=kw.get("slug", "adicao"),
        desc=kw.get("desc", "Descrição"),
        ano_escolar=kw.get("ano_escolar", "1º Ano"),
        seccao=kw.get("seccao", "aprender"),
        disciplina=d,
    )


def _jogo(**kw):
    """Build an unsaved Jogo instance."""
    return Jogo(
        titulo=kw.get("titulo", "Jogo A"),
        descricao=kw.get("descricao", "Desc"),
        publicado=kw.get("publicado", True),
    )


def _livro(**kw):
    """Build an unsaved Livro instance."""
    return Livro(
        titulo=kw.get("titulo", "Livro A"),
        autor=kw.get("autor", "Autor"),
        faixa_etaria=kw.get("faixa_etaria", "6-8"),
        resumo=kw.get("resumo", "Resumo"),
        publicado=kw.get("publicado", True),
    )


def _exercicio(**kw):
    """Build an unsaved Exercicio instance."""
    return Exercicio(
        title=kw.get("title", "Ex 1"),
        level=kw.get("level", 1),
        subject_id=kw.get("subject_id", "matematica"),
        publicado=kw.get("publicado", True),
    )


def _aula(**kw):
    """Build an unsaved Aula instance."""
    return Aula(
        title=kw.get("title", "Aula 1"),
        subject_id=kw.get("subject_id", "matematica"),
        level=kw.get("level", 1),
        publicado=kw.get("publicado", True),
    )


# Disciplin


class DisciplinaListTest(SimpleTestCase):
    """Tests for GET /api/disciplinas/."""

    @patch.object(DisciplinaViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint is publicly accessible and returns HTTP 200."""
        mock_gqs.return_value = [_disciplina()]
        response = self.client.get("/api/disciplinas/")
        self.assertEqual(response.status_code, 200)

    @patch.object(DisciplinaViewSet, "get_queryset")
    def test_returns_all_disciplines(self, mock_gqs):
        """Response body contains every discipline returned by the queryset."""
        mock_gqs.return_value = [
            _disciplina(nome="Matemática", slug="matematica"),
            _disciplina(nome="Português", slug="portugues"),
        ]
        response = self.client.get("/api/disciplinas/")
        self.assertEqual(len(response.json()), 2)

    @patch.object(DisciplinaViewSet, "get_object")
    def test_detail_returns_200(self, mock_get_obj):
        """Detail endpoint returns HTTP 200 when the object exists."""
        mock_get_obj.return_value = _disciplina()
        response = self.client.get("/api/disciplinas/matematica/")
        self.assertEqual(response.status_code, 200)

    @patch.object(DisciplinaViewSet, "get_object")
    def test_detail_unknown_slug_returns_404(self, mock_get_obj):
        """Detail with a slug that doesn't exist returns HTTP 404."""
        mock_get_obj.side_effect = Http404
        response = self.client.get("/api/disciplinas/nao-existe/")
        self.assertEqual(response.status_code, 404)


# Tem


class TemaListTest(SimpleTestCase):
    """Tests for GET /api/temas/."""

    @patch.object(TemaViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint is publicly accessible and returns HTTP 200."""
        mock_gqs.return_value = [_tema()]
        response = self.client.get("/api/temas/")
        self.assertEqual(response.status_code, 200)

    @patch.object(TemaViewSet, "get_queryset")
    def test_returns_all_temas(self, mock_gqs):
        """Response body contains every theme returned by the queryset."""
        mock_gqs.return_value = [
            _tema(titulo="Adição", slug="adicao"),
            _tema(titulo="Subtração", slug="subtracao"),
        ]
        response = self.client.get("/api/temas/")
        self.assertEqual(len(response.json()), 2)


# Jog


class JogoListTest(SimpleTestCase):
    """Tests for GET /api/jogos/."""

    @patch.object(JogoViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint returns HTTP 200."""
        mock_gqs.return_value = [_jogo()]
        response = self.client.get("/api/jogos/")
        self.assertEqual(response.status_code, 200)

    @patch.object(JogoViewSet, "get_queryset")
    def test_returns_all_jogos(self, mock_gqs):
        """Response body contains all games returned by the queryset."""
        mock_gqs.return_value = [_jogo(titulo="A"), _jogo(titulo="B")]
        response = self.client.get("/api/jogos/")
        self.assertEqual(len(response.json()), 2)


# Livr


class LivroListTest(SimpleTestCase):
    """Tests for GET /api/livros/."""

    @patch.object(LivroViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint returns HTTP 200."""
        mock_gqs.return_value = [_livro()]
        response = self.client.get("/api/livros/")
        self.assertEqual(response.status_code, 200)

    @patch.object(LivroViewSet, "get_queryset")
    def test_returns_one_livro(self, mock_gqs):
        """Response body contains the single book returned by the queryset."""
        mock_gqs.return_value = [_livro()]
        response = self.client.get("/api/livros/")
        self.assertEqual(len(response.json()), 1)


# Exercici


class ExercicioListTest(SimpleTestCase):
    """Tests for GET /api/exercicios/."""

    @patch.object(ExercicioViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint returns HTTP 200."""
        mock_gqs.return_value = [_exercicio()]
        response = self.client.get("/api/exercicios/")
        self.assertEqual(response.status_code, 200)

    @patch.object(ExercicioViewSet, "get_queryset")
    def test_response_contains_exercise(self, mock_gqs):
        """Response body contains the exercise returned by the queryset."""
        mock_gqs.return_value = [_exercicio()]
        response = self.client.get("/api/exercicios/")
        self.assertGreaterEqual(len(response.json()), 1)


# Aul


class AulaListTest(SimpleTestCase):
    """Tests for GET /api/aulas/."""

    @patch.object(AulaViewSet, "get_queryset")
    def test_returns_200(self, mock_gqs):
        """List endpoint returns HTTP 200."""
        mock_gqs.return_value = [_aula()]
        response = self.client.get("/api/aulas/")
        self.assertEqual(response.status_code, 200)

    @patch.object(AulaViewSet, "get_queryset")
    def test_response_contains_aula(self, mock_gqs):
        """Response body contains the lesson returned by the queryset."""
        mock_gqs.return_value = [_aula()]
        response = self.client.get("/api/aulas/")
        self.assertGreaterEqual(len(response.json()), 1)


# Auth — Logi


class LoginTest(SimpleTestCase):
    """Tests for POST /api/v1/login."""

    @patch("integrate.auth_views.RefreshToken")
    @patch("integrate.auth_views.authenticate")
    def test_valid_credentials_return_200(self, mock_auth, MockToken):
        """Correct username/password returns HTTP 200 and a success detail message."""
        mock_auth.return_value = MagicMock()
        response = self.client.post(
            "/api/v1/login",
            data={"username": "prof", "password": "pass1234"},
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 200)
        self.assertIn("detail", response.json())

    @patch("integrate.auth_views.authenticate", return_value=None)
    def test_invalid_credentials_return_401(self, _mock_auth):
        """Wrong password returns HTTP 401."""
        response = self.client.post(
            "/api/v1/login",
            data={"username": "prof", "password": "errada"},
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 401)

    @patch("integrate.auth_views.RefreshToken")
    @patch("integrate.auth_views.authenticate")
    def test_sets_access_cookie_on_success(self, mock_auth, MockToken):
        """A successful login sets the access_token cookie."""
        mock_auth.return_value = MagicMock()
        response = self.client.post(
            "/api/v1/login",
            data={"username": "prof", "password": "pass1234"},
            content_type="application/json",
        )
        self.assertIn("access_token", response.cookies)


# Auth — Logou


class LogoutTest(SimpleTestCase):
    """Tests for POST /api/v1/logout."""

    def test_logout_without_token_returns_200(self):
        """Logout always returns HTTP 200, even without an active session."""
        response = self.client.post("/api/v1/logout")
        self.assertEqual(response.status_code, 200)


# Auth — M


class MeTest(SimpleTestCase):
    """Tests for GET /api/v1/me."""

    def test_unauthenticated_returns_401(self):
        """Unauthenticated request to /me is rejected with HTTP 401."""
        response = self.client.get("/api/v1/me")
        self.assertEqual(response.status_code, 401)
