# Generated by Django 6.0.5 on 2026-06-09 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("desc", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("faixa_etaria", models.CharField(blank=True, max_length=50)),
                ("resumo", models.TextField(blank=True)),
                ("temas", models.CharField(blank=True, max_length=500)),
                ("capa", models.ImageField(blank=True, null=True, upload_to="capas/")),
                (
                    "ficheiro",
                    models.FileField(blank=True, null=True, upload_to="livros/"),
                ),
                ("publicado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialOriginal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "ficheiro",
                    models.FileField(blank=True, null=True, upload_to="materiais/"),
                ),
                ("url_externa", models.URLField(blank=True, max_length=500, null=True)),
                ("descarregavel", models.BooleanField(default=False)),
                ("publicado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("online", "Online"), ("imprimivel", "Imprimível")],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("faixa_etaria", models.CharField(blank=True, max_length=50)),
                ("url_externa", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "ficheiro",
                    models.FileField(blank=True, null=True, upload_to="jogos/"),
                ),
                ("publicado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integrate.disciplina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("desc", models.TextField(blank=True)),
                (
                    "ano_escolar",
                    models.CharField(
                        choices=[
                            ("1", "1º Ano"),
                            ("2", "2º Ano"),
                            ("3", "3º Ano"),
                            ("4", "4º Ano"),
                            ("5", "5º Ano"),
                            ("6", "6º Ano"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "seccao",
                    models.CharField(
                        choices=[
                            ("aprender", "Aprender"),
                            ("resolver", "Resolver"),
                            ("ler", "Ler"),
                        ],
                        max_length=20,
                    ),
                ),
                ("publicado", models.BooleanField(default=False)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrate.disciplina",
                    ),
                ),
            ],
            options={
                "unique_together": {("disciplina", "slug", "seccao")},
            },
        ),
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("imagem", "Imagem"),
                            ("video", "Vídeo"),
                            ("pdf", "PDF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("corpo", models.TextField(blank=True)),
                (
                    "ficheiro",
                    models.FileField(blank=True, null=True, upload_to="conteudos/"),
                ),
                ("url_externa", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermédio"),
                            ("avancado", "Avançado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("descarregavel", models.BooleanField(default=False)),
                ("publicado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="integrate.tema"
                    ),
                ),
            ],
        ),
    ]
