# Generated by Django 6.0.5 on 2026-06-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogo",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="materialoriginal",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="tema",
            name="publicado",
        ),
        migrations.AddField(
            model_name="jogo",
            name="tamanho_kb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conteudo",
            name="corpo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="conteudo",
            name="dificuldade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basico", "Básico"),
                    ("intermedio", "Intermédio"),
                    ("avancado", "Avançado"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conteudo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("imagem", "Imagem"),
                    ("video", "Vídeo"),
                    ("pdf", "PDF"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="desc",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="slug",
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="descricao",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integrate.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="faixa_etaria",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="livro",
            name="faixa_etaria",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="livro",
            name="resumo",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="materialoriginal",
            name="autor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="materialoriginal",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="materialoriginal",
            name="ficheiro",
            field=models.FileField(
                blank=True, null=True, upload_to="materiais_originais/"
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="ano_escolar",
            field=models.CharField(
                choices=[
                    ("1º Ano", "1º Ano"),
                    ("2º Ano", "2º Ano"),
                    ("3º Ano", "3º Ano"),
                    ("4º Ano", "4º Ano"),
                    ("5º Ano", "5º Ano"),
                    ("6º Ano", "6º Ano"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="desc",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tema",
            name="seccao",
            field=models.CharField(
                choices=[
                    ("aprender", "Aprender"),
                    ("resolver", "Resolver"),
                    ("ler", "Ler"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="slug",
            field=models.SlugField(max_length=500),
        ),
    ]
