# Generated by Django 6.0.5 on 2026-06-16 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integrate",
            "0002_remove_jogo_tipo_remove_materialoriginal_criado_em_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject_id", models.CharField(max_length=200)),
                ("level", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True, max_length=500, null=True)),
                ("thumbnail_url", models.CharField(blank=True, max_length=500)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("publicado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("level", models.IntegerField()),
                ("subject_id", models.CharField(max_length=200)),
                (
                    "title_color",
                    models.CharField(default="text-blue-600", max_length=200),
                ),
                ("icon_img", models.CharField(blank=True, max_length=500)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("publicado", models.BooleanField(default=False)),
            ],
        ),
    ]
