# Generated by Django 6.0.5 on 2026-06-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrate", "0003_aula_exercicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="ficheiro",
            field=models.FileField(blank=True, null=True, upload_to="aulas/"),
        ),
    ]
