# Generated by Django 6.0.5 on 2026-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrate", "0005_exercicio_jogo_aula_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aula",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="exercicio",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="jogo",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="jogo",
            name="tamanho_kb",
        ),
    ]
