# Generated by Django 6.0.5 on 2026-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrate", "0006_remove_aula_duration_remove_exercicio_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/aulas/"
            ),
        ),
        migrations.AddField(
            model_name="exercicio",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/exercicios/"
            ),
        ),
        migrations.AddField(
            model_name="jogo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/jogos/"
            ),
        ),
    ]
