# Generated by Django 6.0.5 on 2026-06-25 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "integrate",
            "0008_aula_created_by_aula_updated_by_conteudo_created_by_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaterialOriginal",
        ),
    ]
