test-audio:
  curl -X POST http://localhost:8000/api/v1/voice/transcribe/ \
  -F "audio=@srcs/backend/tests/audio_test.webm"

test-audio2:
  curl -X POST http://localhost:8000/api/v1/voice/transcribe/ \
  -F "audio=@srcs/backend/tests/audio_test2.webm"
